### PR TITLE
Fix annoying collision with Array prototype overrides

### LINKED ISSUE #18: o.str.substr is not a function
Error:

```sh
Exception while invoking method 'getHolidays' TypeError: o.str.substr is not a function
     at Parser._shorten (/app/node_modules/date-holidays-parser/lib/Parser.js:192:21)
```
 

with the country 'AT':

```js
const Holidays = require('date-holidays');
let holidays = new Holidays();
holidays.init('AT');
holidays.getHolidays(2020); // ERROR
```

After some debugging:
```js
    key: "_shorten",
    value: function _shorten(o, cap0) {
      console.log({ o, cap0 });
      o.str = o.str.substr(cap0.length, o.str.length);
    }
```
it seems like that `o` and `cap0` are both `function`s!!

Please fix, this is very annoying as this completely breaks the whole library for me 😢

### PR DESCRIPTION
**Pull request by leonidasv**
Fixes https://github.com/commenthol/date-holidays-parser/issues/18

### CODE REVIEW

File: src/PostRule.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ class PostRule {
   _findEventInYear (year, arr) {
     arr = arr || []
     const parser = new Parser()
-    for (const i in arr) {
+    for (const i of arr) {
```
Comment (commenthol) [inline src/PostRule.js]: Can you please change to: 
```js
for (const item of arr) {
      const p = parser.parse(item)
```  
then tests will pass.

File: src/PostRule.js [hunk 2]
```diff
@@ -86,7 +86,7 @@ class PostRule {
...
       const p = parser.parse(arr[i])
```
Comment (leonidasv) [inline src/PostRule.js:90]:
```suggestion
    for (const item of arr) {
      const p = parser.parse(item)
```

**Comment by leonidasv** [comment]
@commenthol Done.
